// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBDqShsBo3qdDg16vKrSLYa62g2-RXkic',
    appId: '1:1022277200410:web:3765f5c2bb9aa6081ebfa3',
    messagingSenderId: '1022277200410',
    projectId: 'connect-37338',
    authDomain: 'connect-37338.firebaseapp.com',
    storageBucket: 'connect-37338.firebasestorage.app',
    measurementId: 'G-8KS2YG40YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkMyv_1dEhQW0TDm01kxg-b-v7LY8AKpM',
    appId: '1:1022277200410:android:a7ce5e19ae1f158e1ebfa3',
    messagingSenderId: '1022277200410',
    projectId: 'connect-37338',
    storageBucket: 'connect-37338.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDJufG57e2AthYkhaV5EZgktJEE-M-sxQ',
    appId: '1:1022277200410:ios:000addc59431c4701ebfa3',
    messagingSenderId: '1022277200410',
    projectId: 'connect-37338',
    storageBucket: 'connect-37338.firebasestorage.app',
    iosBundleId: 'com.example.connect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDJufG57e2AthYkhaV5EZgktJEE-M-sxQ',
    appId: '1:1022277200410:ios:000addc59431c4701ebfa3',
    messagingSenderId: '1022277200410',
    projectId: 'connect-37338',
    storageBucket: 'connect-37338.firebasestorage.app',
    iosBundleId: 'com.example.connect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBDqShsBo3qdDg16vKrSLYa62g2-RXkic',
    appId: '1:1022277200410:web:9decf6d9fb7386091ebfa3',
    messagingSenderId: '1022277200410',
    projectId: 'connect-37338',
    authDomain: 'connect-37338.firebaseapp.com',
    storageBucket: 'connect-37338.firebasestorage.app',
    measurementId: 'G-HE48GT7J8B',
  );

}